# Limites de normalização do Modelo
model:
  t_max: 2880.0
  L_max: 0.05
  Pc_max: 4.0

# Limites da malha física
physics_grid:
  t_points: 200
  L_points: 10
  Pc_points: 10
  L_min: 0.003
  Pc_min: 0.5

# Hiperparâmetros e pesos de cada loss
training:
  epochs: 8000
  learning_rate: 0.001
  lambda_data: 1.0
  lambda_phys: 1.0
  lambda_ic: 10.0

# Referências para visualização de métricas
citrus:
 l_values: [0.003, 0.005, 0.007]
 p_values: [0.8, 1.0, 1.2]
 lins_stop: 1920
 num_points: 120

strawberry:
 l_values: [0.005, 0.007]
 p_values: [3.0]
 lins_stop: 780
 num_points: 60